import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TBW Quote Manager",
  description: "Generated by GC",
  icons: {
    icon: [
      {
        url: '/images/image.png',
        sizes: '32x32',
        type: 'image/png',
      },
      {
        url: '/images/image.png',
        sizes: '16x16',
        type: 'image/png',
      }
    ],
    apple: '/images/image.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/images/image.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="bottom-center" toastOptions={{ duration: 4000 }} />
        {children}
      </body>
    </html>
  );
}
